In [1]:
import numpy as np

In [2]:
np = np.array([1,23,3,4])
print(np)

[ 1 23  3  4]


In [3]:
import numpy as np
#  1D array to 2D array
n = np.array([1,3,4,5,6,78,9,3,2,1,45,65,43,32,2,21])
print("This is the first dimentioanl array ", n)
reshap = n.reshape(2,8)
print("This is the reshape array \n", reshap)

This is the first dimentioanl array  [ 1  3  4  5  6 78  9  3  2  1 45 65 43 32  2 21]
This is the reshape array 
 [[ 1  3  4  5  6 78  9  3]
 [ 2  1 45 65 43 32  2 21]]


In [4]:
# 3D to 1D array pg#111
n = np.array([[[2,3,4],[5,6,7]],[[8,9,6],[56,34,35]]])
print("This is 3 Demension array", n)
reshap = n.reshape(-1)
print("\n3D to convert into 1D array", reshap)

This is 3 Demension array [[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9  6]
  [56 34 35]]]

3D to convert into 1D array [ 2  3  4  5  6  7  8  9  6 56 34 35]


In [5]:
# itrated the 1D array 
n= np .array([1,2,34,45,56,775,23,44])
print("before updating the array", n)
print("itrate")
for a in n:
    print (a)

before updating the array [  1   2  34  45  56 775  23  44]
itrate
1
2
34
45
56
775
23
44


In [6]:
# itrated the 2D array 
n= np .array([[1,2,34,45,56,775,23,44],[2,3,4,4,67,87,54,32]])
print("before updating the 2D Array", n)
print("itrate 2D Array")
for a in n:
    print (a)
print(n.ndim)

before updating the 2D Array [[  1   2  34  45  56 775  23  44]
 [  2   3   4   4  67  87  54  32]]
itrate 2D Array
[  1   2  34  45  56 775  23  44]
[ 2  3  4  4 67 87 54 32]
2


In [7]:
# itrated the 3D array 
n = np .array([[[1,2,34,45,56,775,23,44],[2,3,4,4,67,87,54,32]],[[1,2,34,45,56,775,23,44],[2,3,4,4,67,87,54,32]]])
print("before updating the 3D Array", n)
print("itrate 3D Array")
for a in n:
    print("Each 2D Matrix")
    print (a)
print(n.ndim)

before updating the 3D Array [[[  1   2  34  45  56 775  23  44]
  [  2   3   4   4  67  87  54  32]]

 [[  1   2  34  45  56 775  23  44]
  [  2   3   4   4  67  87  54  32]]]
itrate 3D Array
Each 2D Matrix
[[  1   2  34  45  56 775  23  44]
 [  2   3   4   4  67  87  54  32]]
Each 2D Matrix
[[  1   2  34  45  56 775  23  44]
 [  2   3   4   4  67  87  54  32]]
3


In [8]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.concatenate((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [  3   4   5   8  93 839   4   5   6   4  25 245]


In [9]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.stack((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [[  3   4   5   8  93 839]
 [  4   5   6   4  25 245]]


In [10]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.vstack((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [[  3   4   5   8  93 839]
 [  4   5   6   4  25 245]]


In [11]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.hstack((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [  3   4   5   8  93 839   4   5   6   4  25 245]


In [12]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.dstack((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [[[  3   4]
  [  4   5]
  [  5   6]
  [  8   4]
  [ 93  25]
  [839 245]]]


In [13]:
# join the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
reshap = np.column_stack((n1,n2))
print("After joining the 2 array",reshap)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
After joining the 2 array [[  3   4]
 [  4   5]
 [  5   6]
 [  8   4]
 [ 93  25]
 [839 245]]


In [14]:
# spliting the 1D array
n = np.array([2,3,45,6,65,34,22])
print("Iterating the array")
for a in n:
    print(a)
#  split the array into 2
resarr = np.array_split(n, 2)
print("Array after splitting")
for a in resarr:
    print(a)


Iterating the array
2
3
45
6
65
34
22
Array after splitting
[ 2  3 45  6]
[65 34 22]


In [15]:
# spliting the 1D array( Accessing the individually)
n = np.array([2,3,45,6,65,34,22])
print("Iterating the array")
for a in n:
    print(a)
#  split the array into 2
resarr = np.array_split(n, 2)
print("Accessing the splitting array individually")
print("Array 1 =" ,resarr[0])
print('Array 2 =', resarr[1])


Iterating the array
2
3
45
6
65
34
22
Accessing the splitting array individually
Array 1 = [ 2  3 45  6]
Array 2 = [65 34 22]


In [16]:
# spliting the 1D array( Accessing the individually)
n = np.array([[2,3,45,6,65,34,22],[23,45,66,53,24,21,24]])
print("Iterating the array")
for a in n:
    print(a)
#  split the array into 2
resarr = np.array_split(n, 2)
print("Accessing the splitting array individually")
print("Array 1 =" ,resarr[0])
print('Array 2 =', resarr[1])

Iterating the array
[ 2  3 45  6 65 34 22]
[23 45 66 53 24 21 24]
Accessing the splitting array individually
Array 1 = [[ 2  3 45  6 65 34 22]]
Array 2 = [[23 45 66 53 24 21 24]]


In [17]:
# Search the numpy array from value 
n = np.array([2,3,45,6,53,49])
print(n)
print('itrate the array ')
for a in n:
    print(a)
resarr = np.where(n==45)
print(resarr)

[ 2  3 45  6 53 49]
itrate the array 
2
3
45
6
53
49
(array([2], dtype=int64),)


In [18]:
# Sorting the numpy array
n = np.array([50, 35, 78, 56, 45, 39 ,28])
print("itrate")
for a in n:
    print(a)
print("this is sorted array", np.sort(n))

itrate
50
35
78
56
45
39
28
this is sorted array [28 35 39 45 50 56 78]


In [19]:
n = np.array(['Muzamil','fatima' , 'Mughal', 'mehmoona' , 'farhan'])
print(np.sort(n))

['Mughal' 'Muzamil' 'farhan' 'fatima' 'mehmoona']


In [20]:
n = np.array([[23,45,67,87,45,68],[34,56,78,90,35,26]])
# print(np.sort(n))
print(n.min())
print("print", n.min(axis = 0))
print(n.min(axis=1))

23
print [23 45 67 87 35 26]
[23 26]


In [89]:
# vertical axis (axis 0)
# horizontal axis (axis 1)


In [119]:
# intersect the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
resarr = np.intersect1d(n1, n2)
print("intersect between two array is ", resarr)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
intersect between two array is  [4 5]


In [124]:
# intersect the two numpy array 
n1 = np.array([3,4,5,8,93,839])
n2 = np.array([4,5,6,4,25,245])
print('Iternate first array')
for a in n1:
    print(a)
print('iterate second array')
for a in n2:
    print (a)
resarr = np.setdiff1d(n1, n2)
print(resarr)

Iternate first array
3
4
5
8
93
839
iterate second array
4
5
6
4
25
245
[  3   8  93 839]


In [128]:
# sum the two numpy array 
n1 = np.array([3,4,5,8,93])
n2 = np.array([4,5,6,4,25])
resarr = np.sum([n1, n2])
print(resarr)

157


In [129]:
# Multiply the two numpy array 
n1 = np.array([3,4,5,8,93])
n2 = np.array([4,5,6,4,25])
resarr = np.sum([n1, n2])
print(resarr)

157


In [131]:
# divide the two numpy array 
n1 = np.array([3,4,5,8,93])
n2 = np.array([4,5,6,4,25])
resarr = np.divide(n1, n2)
print(resarr)

[0.75       0.8        0.83333333 2.         3.72      ]


In [134]:
# the two numpy array 
n1 = np.array([3,4,5,8,93])
n2 = np.array([4,5,6,4,25])
n1 = n1 + 2
n2 = n2 +5
# resarr = np.divide(n1, n2)
print(n1)
print(n2)

[ 5  6  7 10 95]
[ 9 10 11  9 30]


In [138]:
# the two numpy array 
n1 = np.array([3,4,5,8,93])
n2 = np.array([4,5,6,4,25])
n1 = n1 + 2
n2 = n2 +5
# resarr = np.divide(n1, n2)
print(np.mean(n1))
print(np.median(n2))
# print(np.mod(n1))

24.6
10.0
